### ISSUE TITLE
Could we add a "download / print" option to the image-caption field also?

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/rr_wp#19]

**Comment by br092616** [comment]
can this be optional?

**Comment by pwrstudio** [comment]
Couldnt you just lright-click > 'save image' if you want to download it?

**Comment by br092616** [comment]
I could but maybe not everyone at any library computer, at least not without explanation, I think that was their idea, because sometimes the images could be mind maps etc

**Comment by pwrstudio** [comment]
okej sure will make it optional

**Comment by pwrstudio** [comment]
Made optional now
