### ISSUE TITLE
editor interface > FORMAT

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/rr_wp#24]
… trying to think trough how the images work also in regard of the editing - and realizing only now how it works.

For the text editor, it would probably make sense to have checkboxes to select the x formats, if possible? If too complicated don’t worry.

**Comment by br092616** [comment]
this is the formats in the text editor? it might be better to have them all the same font and size, with or without checkboxes. and could be move the bold and italics in there as well?

**Comment by br092616** [comment]
and missing an external link format, superscript medium sans serif all caps like the images but no particular color ssigned

**Comment by pwrstudio** [comment]
This is how all external links should be formatted?

**Comment by br092616** [comment]
yes, think so

**Comment by pwrstudio** [comment]
changed the styling of links now:

![screen shot 2016-09-14 at 6 31 37 pm](https://cloud.githubusercontent.com/assets/8209990/18520771/821e8cd0-7aa9-11e6-9bec-653643cfc566.png)

**Comment by pwrstudio** [comment]
Regarding the other changes to the editor: there does not seem to be away to change the drop down menu to buttons or style the text in the menu itself.

**Comment by br092616** [comment]
could you change the link size and position to the following please

![screen shot 2016-09-16 at 7 29 47 am](https://cloud.githubusercontent.com/assets/22127585/18576170/6655b2ee-7bdf-11e6-97ba-34a4b16b1500.png)

**Comment by br092616** [comment]
and I guess those links should be black and turn blue on hover

**Comment by pwrstudio** [comment]
done

**Comment by manegame** [comment]
Looks fixed. I will close this to keep things clear.
