### ISSUE TITLE
Change structure Understandings

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/rr_wp#30]
**Understanding: Title
— Knowing and Doings
— Close Reading
— — Knowing 
— — Doing
—  Making Connections
— — Knowing 
— — Doing
— Debatable Question
— — Knowing 
— — Doing**

**Comment by br092616** [comment]
- if you look at the draft for the new version of understandings, there is one “understandings” that was missing, trying to add it with the editor didn’t really do it so far… would you have a look? Sorry I didn't see this list when reading your email!

**Comment by br092616** [comment]
also if you look at the draft, it's behaves more like a waterfall with the blue...  single pages turn blue and stay blue when moving along

**Comment by br092616** [comment]
so this would be

Understandings
Understanding: Title
— Knowing and Doings
— — Close Reading > Knowing
— — Close Reading > Doing
— — Making Connections > Knowing
— — Making Connections > Doing
— — Debatable Question > Knowing
— — Debatable Question > Doing

**Comment by br092616** [comment]
added content accordingly - would be great if you could combine the doubling elements following the draft, if possible; so it' eiter "**close reading > knowing** > doing" or "**close reading** > knowing **> doing**"

**Comment by br092616** [comment]
sorry, you can take out the automatic "understanding" in "Understanding: Reading is a creative act", we can add it manually.
and then for the styling it would more look like this for example (bold is blue) 

**Understandings
Understanding: Title
— Knowing and Doings
— — Close Reading** > Knowing ... or **Close Reading > Doing**
— — Making Connections > Knowing ... or Making Connections > Doing
— — Debatable Question > Knowing ... or Debatable Question > Doing

or 

**Understandings
Understanding: Title
— Knowing and Doings**
— — Close Reading > Knowing ... or Close Reading > Doing
**— — Making Connections > Knowing** ... or Making Connections > Doing
— — Debatable Question > Knowing ... or Debatable Question > Doing

**Comment by pwrstudio** [comment]
I have changed the waterfall-marking with blue now.

In order to get the structure in the draft you need to position posts as sub-posts to each other:

**Comment by pwrstudio** [comment]
Easiest way to change the parent of a post is to go to "Quick Edit":

![screen shot 2016-09-12 at 20 22 14](https://cloud.githubusercontent.com/assets/8209990/18447375/ae843dbc-7926-11e6-983f-04a7cb59fbe9.png)

**Comment by br092616** [comment]
if you look at the draft, for the menu could we change here so that in the case of the image, for example, everything is blue up to where you actually are - so Understandings and Knowings and Doings would be blue as well here...

![screen shot 2016-09-13 at 8 08 40 am](https://cloud.githubusercontent.com/assets/22127585/18463311/82a28a1a-7989-11e6-9104-0729301c7d99.png)

**Comment by br092616** [comment]
great thanks - please make the links turn blue also on hover

**Comment by br092616** [comment]
not sure why but content on http://52.91.41.41/understandings/#understanding wouldn't display

**Comment by pwrstudio** [comment]
What does the last comment here refer to? Is this still the case?

**Comment by br092616** [comment]
yes still the case, the text in "Understanding: Reading is a creative act" won't show over here?

for the menu if possible it should be that under "Konwings and Doings", "Close reading" is either one unit with "Knowing" or "Doing". Was like that at some point I think? Thanks!

**Comment by br092616** [comment]
all great only the text in "Understanding: Reading is a creative act" won't display

for the menu, it would be great I think if the hover would already combine both elements: either "**Close Reading>Knowing**>Doing" or "**Close Reading**>Knowing**>Doing**"

**Comment by br092616** [comment]
the prompts won't display I think?

**Comment by br092616** [comment]
Alejandro was wondering why the text in "Understanding: Reading is a creative act" won't display

**Comment by br092616** [comment]
I don't understand to be honest - it was working perfectly just as in the
last draft at some point last week?

**Comment by br092616** [comment]
the empty posts with two - - shouldn't be clickable by themselves, only in combination with either knowing or doing. thanks!

**Comment by pwrstudio** [comment]
OK, referring to manus's diagram above:

**– (one dash)** = Clickable, blue on hover
**– – (two dashes)** = NOT clickable, nothing happens on hover
**– – –(three dashes)** = Clickable, blue on hover, closest two-dash item blue on hover

Should work like this now. Sorry for confusion.

The content of one-dash items (such as "Reading is a creative act") now show. my bad.

– – –

Prompts show now. 

– – –

Hovering on sub-menu (eg. 'Doing') will highlight the parent now.

**Comment by br092616** [comment]
thanks, apologies if the design was not clear enough. only highlighting the
grandparent now?

to be sure: the idea was that (two dashes), not clickable on its own,
hovers along with either of the two (three dashes). and when clicking one
of the (three dashes), stays blue with it...

**Comment by br092616** [comment]
looking great now - only the "understandings" is missing at the top, as a landing page in understandings
