### ISSUE TITLE
left and right typography

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#41]
- sorry to be asking for single pixels, but would be great it it would be the same line height/line left and right here. On the righ the size is 23 px, too? Let me know if too annoying...
![screen shot 2016-09-11 at 6 52 12 pm](https://cloud.githubusercontent.com/assets/22127585/18419316/216e62aa-7858-11e6-9df8-8f0997151ba9.png)

**Comment by pwrstudio** [comment]
Line height is 24px throughout.
