### ISSUE TITLE
http://www.artresourcestransfer.org/readingresources

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#43]
curious to know when it will be accessible on http://www.artresourcestransfer.org/readingresources, you haven’t had news I imagine?

**Comment by pwrstudio** [comment]
No word, will mail a gain and see....

**Comment by br092616** [comment]
not sure where we are with this? thx

**Comment by pwrstudio** [comment]
mailed cooper again....

**Comment by br092616** [comment]
I don't quite understand I'm afraid, not sure if Cooper talked to Alejandro about the eventual address or reading resources - I thought it will be http://www.artresourcestransfer.org/readingresources but it's resources.artresourcestransfer.org - you don't know either I assume? I might ask Alejandro? thx
