### ISSUE TITLE
display on old pcs with new browsers

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#45]
something to keep in mind?
![img_2651](https://cloud.githubusercontent.com/assets/22127585/18419378/9d1b1ece-7859-11e6-96d4-d3ba85f04fe7.JPG)
![img_2652](https://cloud.githubusercontent.com/assets/22127585/18419380/9d1d690e-7859-11e6-85d8-8e9781f7ed2a.JPG)
![img_2653](https://cloud.githubusercontent.com/assets/22127585/18419382/9d1f0d4a-7859-11e6-9fd8-6ac8d7cfa894.JPG)
![img_2654](https://cloud.githubusercontent.com/assets/22127585/18419381/9d1ea620-7859-11e6-8d12-3de048e006b5.JPG)
![img_2656](https://cloud.githubusercontent.com/assets/22127585/18419379/9d1c67ac-7859-11e6-8561-580b7f6b80de.JPG)

**Comment by pwrstudio** [comment]
I think this might be fixed now. Used another less modern technique for the centering. Will check on older browsers later today....

**Comment by br092616** [comment]
just checked again before leaving the library - using an old machine, like some of underserved communities libraries might use them… not sure how important this is really. if too much then I’ll just let Alejandro know and he can do a few tests also, before you spend more time with it

**Comment by pwrstudio** [comment]
did the site work now in the library?

**Comment by br092616** [comment]
still not working I'm afraid 

![img_2696](https://cloud.githubusercontent.com/assets/22127585/18576984/9f2b6b5c-7be6-11e6-81d8-1838ceefe36b.JPG)
![img_2695](https://cloud.githubusercontent.com/assets/22127585/18576985/9f2ee908-7be6-11e6-818e-5cd6d4768e0a.JPG)

**Comment by br092616** [comment]
I asked Alejandro to have a look also, let's see if something comes up?
