### ISSUE TITLE
lightbox

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#46]
could you change to "no background", hsla(0, 0%, 100%, 0) none repeat scroll 0 0

**Comment by pwrstudio** [comment]
So, a completely transparent/invisible background?

**Comment by br092616** [comment]
could the captions sit always on the left edge of the image?

**Comment by br092616** [comment]
yes transparent

**Comment by br092616** [comment]
only the caption needs a white background I think

**Comment by pwrstudio** [comment]
Regarding the caption: yes, it was like that before, and is now again. Problem is just that the type face turns blurry when I position it in this way... not sure why but it is a know bug:
http://stackoverflow.com/questions/31109299/css-transform-translate-50-50-makes-texts-blurry
Will try to fix!

**Comment by br092616** [comment]
could you change the line height of the captions to 20px, and the bottom-padding of the image from 24px to 14px

**Comment by manegame** [comment]
captions left align, line height and padding adjusted
Please change in WP backend: Custom fields > Texts + Notes + Images > Images > Captions > textarea for proper download links

**Comment by br092616** [comment]
please take out the white background in the captions, let's see how far we get without

**Comment by manegame** [comment]
done

**Comment by br092616** [comment]
- in bibliography, when the image is open, please take out the opacity on the image in the background
![screen shot 2016-09-13 at 7 32 23 am](https://cloud.githubusercontent.com/assets/22127585/18462922/9f3b6b86-7986-11e6-8434-7c0625fe6e99.png)

- the aligned captions come with the next upload?

- somehow the navigation icons display larger than they are, they should all display with 24px; and I'm sorry there was one mistake with them, here's the new ones thanks!

![close_hover](https://cloud.githubusercontent.com/assets/22127585/18463030/5d2cf0d8-7987-11e6-8ada-b279d233acaa.png)

![close](https://cloud.githubusercontent.com/assets/22127585/18463028/5d298ce0-7987-11e6-8f5f-922d3133712e.png)

![left_hover](https://cloud.githubusercontent.com/assets/22127585/18463029/5d2a4ed2-7987-11e6-9ece-e5c8aa2536b9.png)

![left](https://cloud.githubusercontent.com/assets/22127585/18463031/5d3f0e9e-7987-11e6-97fc-8b6490eb4d11.png)

![right_hover](https://cloud.githubusercontent.com/assets/22127585/18463032/5d414ce0-7987-11e6-88db-33a92eb92deb.png)

![right](https://cloud.githubusercontent.com/assets/22127585/18463033/5d4358c8-7987-11e6-8da4-0484fca5d282.png)

**Comment by br092616** [comment]
the white background will be gone with the new upload also? thx

**Comment by br092616** [comment]
i guess the large image would need to close also when clicking on the image - or anywhere in the background actually.

how about the caption, if too complicated to have it align with the image please let me know.

![screen shot 2016-09-13 at 8 02 35 am](https://cloud.githubusercontent.com/assets/22127585/18463207/92b0fdfc-7988-11e6-94c3-01941b022700.png)

**Comment by br092616** [comment]
btw now the image again seems to be on top of the type? hasn't it been different in the meantime?

![screen shot 2016-09-13 at 8 48 57 am](https://cloud.githubusercontent.com/assets/22127585/18464103/2c6e7c98-798f-11e6-985a-375a91887b0b.png)

**Comment by br092616** [comment]
for the caption please change to line height 18px thx!

**Comment by br092616** [comment]
if you go to http://52.91.41.41/about-reading-resources/#, there should be a second image that won't display? Not sure if I'm missing something?

**Comment by br092616** [comment]
oh they are on top of each other - they should both be where the image-footnotes are.

and could the download link turn blue on hover?

**Comment by br092616** [comment]
something funny with the first image that opens large?

![screen shot 2016-09-13 at 2 29 24 pm](https://cloud.githubusercontent.com/assets/22127585/18475772/102b35f6-79c8-11e6-84bf-9bd7fe13284c.png)

**Comment by br092616** [comment]
for the image captions - if too difficult to adjust to the edge of the image, we might put them always the same width as the prompt-box...

**Comment by pwrstudio** [comment]
The lightbox image should be opening in the center consistently now. Captions are aligned. will close this issue if nothing else comes up.

**Comment by br092616** [comment]
great, wondering earlier if there’s a transition effect still that makes them move vertically when opening… if yes please remove

**Comment by pwrstudio** [comment]
there should not be now. was a side-effect of the centering...

**Comment by br092616** [comment]
it seems the icons I sent are not online yet - let me send again to be sure. 


![close_hover](https://cloud.githubusercontent.com/assets/22127585/18463030/5d2cf0d8-7987-11e6-8ada-b279d233acaa.png)

![close](https://cloud.githubusercontent.com/assets/22127585/18463028/5d298ce0-7987-11e6-8f5f-922d3133712e.png)

![left_hover](https://cloud.githubusercontent.com/assets/22127585/18463029/5d2a4ed2-7987-11e6-9ece-e5c8aa2536b9.png)

![left](https://cloud.githubusercontent.com/assets/22127585/18463031/5d3f0e9e-7987-11e6-97fc-8b6490eb4d11.png)

![right_hover](https://cloud.githubusercontent.com/assets/22127585/18463032/5d414ce0-7987-11e6-88db-33a92eb92deb.png)

![right](https://cloud.githubusercontent.com/assets/22127585/18463033/5d4358c8-7987-11e6-8da4-0484fca5d282.png)

**Comment by manegame** [comment]
Hey, I changed SVG's to match this. Is it good?

**Comment by br092616** [comment]
yes thanks!

**Comment by br092616** [comment]
the image within the text won't open on my pc nor on my phone... the ones in bibliography open but the fist one not centered, not on the pc nor the phone. does the function with the two images within the text work properly now? let me know, thank yuo!

**Comment by pwrstudio** [comment]
Images within the text work now. Multiple images work too.

Images open centered now again. (fixing one thing broke another....)

**Comment by br092616** [comment]
great thanks!

**Comment by br092616** [comment]
let me know if I you want me to wait with looking at it - right now the
images open centerd, but the effect is there still, moving by about 20px or
so. looking great otherwise!

**Comment by pwrstudio** [comment]
wierd. i know where this problem comes from. and i believe it is fixed. not seeing it here on chrome/firefox. what browser are you on?

**Comment by br092616** [comment]
chrome/firefox on a windows pc!

**Comment by br092616** [comment]
still moving on my mac and phone, too
