### ISSUE TITLE
Center dashed line not showing up in Firefox

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/rr_wp#47]
The scrollbar is not hidden as it is in chrome/safari: 

![screen shot 2016-09-11 at 19 45 57](https://cloud.githubusercontent.com/assets/8209990/18419452/7ace9f9c-785b-11e6-80f7-5522450d5cfb.png)

**Comment by br092616** [comment]
working now over here

**Comment by manegame** [comment]
Fixed
