### ISSUE TITLE
top menu behaviour

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#48]
when open and clicking sub menus on the left hand side, the top menu won't close

**Comment by pwrstudio** [comment]
You mean it should close when you click for.ex. *how* on the left hand side here?

![screen shot 2016-09-11 at 20 18 02](https://cloud.githubusercontent.com/assets/8209990/18419507/f16091d2-785c-11e6-99cf-cad97131da58.png)

**Comment by br092616** [comment]
yes

**Comment by pwrstudio** [comment]
Changed
