### ISSUE TITLE
overall typography 

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#50]
it’s quite nice I think they’ll have fun with this

- can we add the indent also to the small format? and if you look at http://52.91.41.41/#who, it's not there either?

- there's a spacing above the first line here http://52.91.41.41/understandings/ that should not be there

- sorry: please change the line height of the large text to 25px

- the prompt shouldn’t have the image navigation, just click by clicking the background (can apply to all images also but with the green navigation also)

- it would be nice to have the prompts grey and then on hover turn orange, then stay orange when the book is there (see pdf)

- there is two different blues I think?

![screen shot 2016-09-11 at 11 18 18 pm](https://cloud.githubusercontent.com/assets/22127585/18420599/783c976e-7876-11e6-8ce2-153a1d8db6d1.png)

**Comment by br092616** [comment]
- could you please change the line height of the small text to 22px... maybe better then to adjust the footnotes to the same also (sorry for back and forth)

**Comment by pwrstudio** [comment]
## Blue: 
yes very strange. They do look different but are in fact the same color-code:

![screen shot 2016-09-12 at 19 41 26](https://cloud.githubusercontent.com/assets/8209990/18446252/dcb9f71c-7921-11e6-99a7-e21a2a9c3219.png)

![screen shot 2016-09-12 at 19 41 39](https://cloud.githubusercontent.com/assets/8209990/18446258/e7329c12-7921-11e6-842d-0452254726b5.png)

Will see what might cause this...

## Indent of small text
Should work already.
for example on understanding: Reading is a creative act > close reading > knowing
http://52.91.41.41/understandings/#understanding-close-reading-2-knowing

![screen shot 2016-09-12 at 19 50 27](https://cloud.githubusercontent.com/assets/8209990/18446400/776226c2-7922-11e6-8175-b13a8064089b.png)

## Spacing above first line on understandings page
Should be fixed now.

## 25px line-height
Changed.

## Prompt-color
Changed

## Prompt close
Changed

**Comment by pwrstudio** [comment]
## 20px line-height for small text
Changed

**Comment by br092616** [comment]
the paragraphs (except the first ones) should have an indent. or am I missing something in the editor?

![screen shot 2016-09-13 at 7 59 17 am](https://cloud.githubusercontent.com/assets/22127585/18463111/28573c3c-7988-11e6-95f6-b39a88b49faa.png)

**Comment by br092616** [comment]
the bold format (headlines on the right) won't display in firefox I think, at least for the small format?

![screen shot 2016-09-13 at 8 13 09 am](https://cloud.githubusercontent.com/assets/22127585/18463407/2d1bf710-798a-11e6-932b-300ad0b4a173.png)

**Comment by br092616** [comment]
the bold format won't apply to the external links here. also they should be blue

![screen shot 2016-09-13 at 8 29 22 am](https://cloud.githubusercontent.com/assets/22127585/18463707/4bc1893a-798c-11e6-8df7-eb4f6ddc84cc.png)

**Comment by br092616** [comment]
and the line height for the small text should be 22px, as in the footnotes.

noted that here the footnotes should be 16px not 14px

![screen shot 2016-09-13 at 8 32 09 am](https://cloud.githubusercontent.com/assets/22127585/18463763/b438ba88-798c-11e6-98ec-8450043a26b4.png)

**Comment by br092616** [comment]
looked at the colors again, could we try 

blue 016cf9
orange fe9e1a

thanks!

**Comment by br092616** [comment]
of I use the bold on the small sans serif it looks strange (http://52.91.41.41/guiding-question/#how-can-the-masters-tools-dismantle-the-masters-house-about-the-text) - maybe you could assign the medium sans serif here?

**Comment by br092616** [comment]
also on http://52.91.41.41/guiding-question/#how-can-the-masters-tools-dismantle-the-masters-house-about-the-text if you look at the footnotes, it seems the indent of the first line doesn't match the indent of the following by a few pixels at least? thx

**Comment by br092616** [comment]
working on other options for formats... i noticed the type looks quite blurry on the edges, don't you think? except in safari there it's more the other extreme, a little thin. wondering if there's something that could be done about that. 

![screen shot 2016-09-13 at 4 27 33 pm](https://cloud.githubusercontent.com/assets/22127585/18477832/5432b506-79cf-11e6-8da2-2cfa77191482.png)

**Comment by br092616** [comment]
only noticing now - in the draft the all caps is small caps actually. is there an option for small caps at all, if yes would be great if you could add that to the formats

**Comment by br092616** [comment]
in the editor when applying the indent in the second paragraph there is a strange extra line still, for example 52.91.41.41/understandings/#understandings

**Comment by br092616** [comment]
for the top margins of the columns and also the top menu, please change 96 to 116px and top-menu to 38px

![screen shot 2016-09-13 at 5 20 18 pm](https://cloud.githubusercontent.com/assets/22127585/18479796/9b223bd8-79d6-11e6-9d98-1ff431474527.png)
![screen shot 2016-09-13 at 5 20 26 pm](https://cloud.githubusercontent.com/assets/22127585/18479794/9af8b588-79d6-11e6-93b0-e707fe68612b.png)

**Comment by br092616** [comment]
and position artresourcestransfer to 20px left and 25 top thx!

**Comment by br092616** [comment]
on the right the first two paragraph have different line height, can't figure why

http://52.91.41.41/understandings/#understanding-knowing

**Comment by br092616** [comment]
no priority...  could you change the indent for the large text to 26px please

**Comment by br092616** [comment]
please change the indent for small text to 22px

**Comment by pwrstudio** [comment]
i have commented on the individual comments above. let me know if there are any more typo-problems.

**Comment by br092616** [comment]
- please change line height of large serif to 26px (For Alejandro)

**Comment by br092616** [comment]
- please change the small format that Alejandro has been using as small caps to 

.capitals {
    letter-spacing: 0.1em;
    text-transform: uppercase;
}
.orange {
    color: #fe9e1a;
}
.small, .small-text {
    font-size: 1.15em; (does this make sense at all - the idea is a size between 16px and 17px…?)
    line-height: 22px !important;

**Comment by br092616** [comment]
- please ad a “green” format, and change the black external links to green

**Comment by br092616** [comment]
another detail: the art resources transfer should open in new tab and, could it be a little bit smaller, same as on the actual website?

**Comment by manegame** [comment]
Changes applied

**Comment by br092616** [comment]
can't see green external links turning blue...?

**Comment by br092616** [comment]
please disregard all above and change, (listing from above what still was open, and one new thing)
- line height large serif to 26px
- make external links green, change font-size from 80% to 74%
- if possible, only for the fake small all caps, change font size to 17px
thanks!

**Comment by br092616** [comment]
there seems to be one line too on the left hand side in bibliography - between quote and 'image'

**Comment by pwrstudio** [comment]
typo changes made
