### ISSUE TITLE
structure guiding questions

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#51]
if you look at the draft, the for guiding questions the initial page is this here, not sure how we could do that with them menu as it is now?

![screen shot 2016-09-13 at 8 05 50 am](https://cloud.githubusercontent.com/assets/22127585/18463276/20e5276a-7989-11e6-92e5-174c2e9da0ae.png)

**Comment by br092616** [comment]
oh and I only realize this now, if you look at the draft, the idea was to have an image with the guiding question

**Comment by br092616** [comment]
changed the text and deleted two footnotes - the numbers remain after updating

**Comment by pwrstudio** [comment]
Re: footnotes: you have to also remove the textbox itself by clicking the minus-sign:
![screen shot 2016-09-13 at 5 41 41 pm](https://cloud.githubusercontent.com/assets/8209990/18482904/47051dd4-79e2-11e6-9606-353a832cbd52.png)

**Comment by br092616** [comment]
to be sure: either text or image should be blue, along with the quote. the landing from the top menu would be the blue quote and the blue text about painting...

**Comment by pwrstudio** [comment]
The blue-marking of the menu should now be correct.
will add the footnote image to the menu now....

**Comment by pwrstudio** [comment]
optional image footnote added to guiding question menu

**Comment by br092616** [comment]
there's a break in the "question", could it run in one line?

![screen shot 2016-09-16 at 7 12 04 am](https://cloud.githubusercontent.com/assets/22127585/18575976/50f53430-7bdd-11e6-8b7e-9445ce810041.png)

**Comment by br092616** [comment]
landing on "guiding question", both text display. should just be "about the painting"

**Comment by pwrstudio** [comment]
should be just 'about painting now'

**Comment by br092616** [comment]
from Alejandro:

In GUIDING QUESTION
Please make "“How can the master’s tools dismantle the master’s house?”" black
and leave space between this and About Painting About Text

**Comment by br092616** [comment]
the black question shoulnd't at all be clickable, if possible

**Comment by br092616** [comment]
it was correct in the meantime, now not quite right...
