### ISSUE TITLE
download / print option

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#52]
if you look at the draft, there's an (optional) option to add a download / print button towards the bottom on the right hand side. it would create a pdf of the content you're seeing on that page. I didn't mention it specifically, hope it's ok to add - and not sure if there's a way to get the styles to the pdf, and have a sort of template - that might look something like this... let me know!

![screen shot 2016-09-13 at 5 09 10 pm](https://cloud.githubusercontent.com/assets/22127585/18479331/e80f7d18-79d4-11e6-960c-7d7b21bdbd0e.png)

[readingresources_download_0812.pdf](https://github.com/pwrstudio/rr_wp/files/470153/readingresources_download_0812.pdf)

**Comment by pwrstudio** [comment]
I am not really sure how to generate a styled pdf form wordpress. what i can offer is an option of downloading a pre-made pdf or other file.

**Comment by br092616** [comment]
ok, this can simply be an external link?

**Comment by pwrstudio** [comment]
It can, yes. Or a file-upload. Or both.
