### ISSUE TITLE
issues from Alejandro

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#53]
- please change menu and marker-menu position to y=46px
- please change left and right column padding top to y=136px
- another detail: the art resources transfer should open in new tab and, and be identical exactly same size as on A.R.T. website

**Comment by br092616** [comment]
won't open in a new tab I thinK?

**Comment by br092616** [comment]
@pwrstudio also the external links should open in new tab please

**Comment by br092616** [comment]
... now that the menu sits a little lower, let's also change the a.r.t. logo y-position from 25px to 32px

**Comment by manegame** [comment]
Done

**Comment by br092616** [comment]
forgive me - I think ,it's still at 25px not 32px?
