### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#55]
it might be nice to add some white space a the bottom, maybe 60px or so?

**Comment by pwrstudio** [comment]
There is a 96px padding added to the bottom of each column already:

![screen shot 2016-09-20 at 8 57 08 am](https://cloud.githubusercontent.com/assets/8209990/18653966/4a2144b0-7f10-11e6-9dec-9d6437c459a9.png)

**Comment by pwrstudio** [comment]
Or do you mean something else?

**Comment by br092616** [comment]
sorry I was confused, looked at it on an old pc
