### ISSUE TITLE
dashboard, pages

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#56]
would it be possible to reduce the height of "title caption" text field by half, and double the height of the "Text" Textfield?

**Comment by pwrstudio** [comment]
cant change size of title caption.
'text' field can be pulled to enlarge though:

![screen shot 2016-09-23 at 11 18 31 am](https://cloud.githubusercontent.com/assets/8209990/18773211/9208b44a-817f-11e6-9f0a-d060bf7e5095.png)

**Comment by pwrstudio** [comment]
lower right corner in screenshot above
