### ISSUE TITLE
last changes top menu

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#57]
sorry, five numbers...

<img width="1368" alt="screen shot 2016-09-23 at 16 23 57" src="https://cloud.githubusercontent.com/assets/22127585/18789243/930c6596-81aa-11e6-8600-5f6c886dd7bc.png">
<img width="1368" alt="screen shot 2016-09-23 at 16 24 25" src="https://cloud.githubusercontent.com/assets/22127585/18789244/9312e6d2-81aa-11e6-885c-8476c13bd5de.png">
<img width="1368" alt="screen shot 2016-09-23 at 16 24 35" src="https://cloud.githubusercontent.com/assets/22127585/18789245/93161cc6-81aa-11e6-94c5-80ac00ee61e1.png">

and

<img width="1368" alt="screen shot 2016-09-23 at 16 27 53" src="https://cloud.githubusercontent.com/assets/22127585/18789287/bedd165c-81aa-11e6-8818-620b5fc32f22.png">
![Uploading Screen Shot 2016-09-23 at 16.28.02.png…]()

thanks!

**Comment by pwrstudio** [comment]
Does this one only apply to the last menu item?

<img width="1368" alt="bedd165c-81aa-11e6-8818-620b5fc32f22" src="https://cloud.githubusercontent.com/assets/8209990/18791200/53551558-81e4-11e6-94d8-4ec109568849.png">

also: this last one seem to have not uploaded properly:

![screen shot 2016-09-23 at 11 20 33 pm](https://cloud.githubusercontent.com/assets/8209990/18791218/5fbdbdfe-81e4-11e6-9cbb-2af2cd292fa4.png)

**Comment by br092616** [comment]
oh only about and colophon each on the outside, to center them more evenly thanks!

**Comment by pwrstudio** [comment]
got it...
