### ISSUE TITLE
change header margins once again

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#58]
five numbers, thanks!
(please let me know if you want me to change myself on the ftp)

<img width="1170" alt="screen shot 2016-09-27 at 08 32 37" src="https://cloud.githubusercontent.com/assets/22127585/18862617/a081bfd8-848d-11e6-9994-b1eb8f4bd27c.png">
<img width="1170" alt="screen shot 2016-09-27 at 08 32 50" src="https://cloud.githubusercontent.com/assets/22127585/18862624/a426f27a-848d-11e6-97fe-f115aeb0fef6.png">
<img width="1170" alt="screen shot 2016-09-27 at 08 33 03" src="https://cloud.githubusercontent.com/assets/22127585/18862629/aa465466-848d-11e6-8dc0-460ae154806f.png">
<img width="1170" alt="screen shot 2016-09-27 at 08 36 54" src="https://cloud.githubusercontent.com/assets/22127585/18862633/b02b03a4-848d-11e6-872d-737508b200fa.png">
<img width="1170" alt="screen shot 2016-09-27 at 08 37 05" src="https://cloud.githubusercontent.com/assets/22127585/18862634/b22ea11a-848d-11e6-9103-d79fecbbdbd7.png">

**Comment by br092616** [comment]
would be great it you could do those - haven't heard from Alejando yet.

Thanks!
B

**Comment by br092616** [comment]
and this, from Alejandro. Plus a few more issues coming up hope that's ok

<img width="1240" alt="screen shot 2016-10-02 at 07 25 32" src="https://cloud.githubusercontent.com/assets/22127585/19018883/94f8953c-8871-11e6-81e2-3e841cb8da0c.png">

**Comment by pwrstudio** [comment]
Changes made
