### ISSUE TITLE
more changes

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#61]
How far do we get with 150 euro more on your side? They say unfortunately they are tight with the budget. But working on the next season already...

- set ART logo similar to ART website, not as svg if possible (let's just put it 118px from left)
- put columns with 185px padding-top
- in the main menu, Activating the Catalogue should come after Ways of Reading
- no blue text in right column, all black
- put footnotes in texts, prompts, and external links all bold black sans serif (as external links are now) and turn green on hover
- treat footnotes like prompts
- put prompts (and footnotes) text and box green 
- set prompt box width to 520px
- set image opacity for images behind text to 0.18
- Guiding Question-Question and "Understanding" in Understandings should be blue and active when coming from the main menu, but then turn black when selecting another sub-menu below
- add italics to formats (do you have the cut already?
[Nimbus Roman D OT Regular Italic.zip](https://github.com/pwrstudio/rr_wp/files/514631/Nimbus.Roman.D.OT.Regular.Italic.zip)
- somethings funny with the menu when we were looking at it, that the colophon appeared on the far left side, for example
- http://resources.artresourcestransfer.org/guiding-question/ the image isn't working correctly - yesterday we thought it should be like a regular grey image sitting somewhere in the right column (maybe I can position it by editing the text field with spaces only, and then add an image link?), then behave as an image within a text - not as the bibliography actually...

hope it's not too confusing, we should be there soon. thank you!

**Comment by br092616** [comment]
- update: put footnotes in texts, prompts, and external links all bold black superscript sans serif (as external links are now only black) and turn green on hover

**Comment by pwrstudio** [comment]
Changes made now!

Some notes:

> in the main menu, Activating the Catalogue should come after Ways of Reading

changed. this can be done in the admin area by dragging the posts in the "All posts" view

> http://resources.artresourcestransfer.org/guiding-question/ the image isn't working correctly

works now. for some reason the image disappeared if it is aligned to close to the left edge of the column - only way i found to fix this is by enabling the source code view in the editor. Through this you can edit the left and top padding to put the image where you want it within the column:

![screen shot 2016-10-07 at 10 14 49 pm](https://cloud.githubusercontent.com/assets/8209990/19205479/093bbbac-8ce3-11e6-8cdb-0155b4e36bc0.png)

**Comment by pwrstudio** [comment]
I believe the remaining inconsistencies with the colors/styling of the text are due to styles applied in the editor.

**Comment by br092616** [comment]
great thanks! only the image won't behave like the other images within texts on hover?

**Comment by br092616** [comment]
let's put all links, footnotes, prompts #d4d4d4, turn black on hover

**Comment by br092616** [comment]
it'll be a nice site!

**Comment by br092616** [comment]
the color of the a.r.t. logo is #474747

**Comment by br092616** [comment]
the font size of the a.r.t. logo is 14px I think

**Comment by pwrstudio** [comment]
Changes made!

**Comment by br092616** [comment]
plus one... could we change the padding right of the right column from 90 to 96px, please

**Comment by br092616** [comment]
i think for the large text the footnotes are too high, can we change this also to -6px instead of -10px

<img width="1292" alt="screen shot 2016-10-08 at 12 33 20" src="https://cloud.githubusercontent.com/assets/22127585/19212538/8127963e-8d53-11e6-900e-369ce9421966.png">

**Comment by br092616** [comment]
if you look in http://resources.artresourcestransfer.org/understandings/#we-shape-the-stories-we-tell-about-ourselves-through-the-words-of-others-translation-knowings, the prompt is black still, not grey

**Comment by br092616** [comment]
sorry - not if the prompt is open it is orange in the text... almost there. could the prompts turn green on hover, and then stay green instead of orange? and in the text editor it tuns orange, maybe it would be good to take that out as well... thx!

**Comment by br092616** [comment]
<img width="1292" alt="screen shot 2016-10-08 at 12 45 56" src="https://cloud.githubusercontent.com/assets/22127585/19212618/7e884994-8d55-11e6-8463-c4817771cfdd.png">

**Comment by pwrstudio** [comment]
should be fixed now

**Comment by br092616** [comment]
could we add 0.02em letter-spacing to the italics…?


benedikt reichenbach 
www.benediktreichenbach.com 
+49 1 76 23 92 74 56

**Comment by pwrstudio** [comment]
done

**Comment by pwrstudio** [comment]
but the site is contructed to have the understandings stuctured like in this section:

![screen shot 2016-10-08 at 3 48 55 pm](https://cloud.githubusercontent.com/assets/8209990/19213530/c53cbec4-8d6e-11e6-8987-f780f1057c09.png)

![screen shot 2016-10-08 at 3 49 35 pm](https://cloud.githubusercontent.com/assets/8209990/19213542/e7b90520-8d6e-11e6-912e-02cd1767a10d.png)

**Comment by br092616** [comment]
sorry - they thought it would make more sense like now in the first one. with the doings next to each other in one line actually...

**Comment by br092616** [comment]
I thought we could make it work somehow with what we have, in terms of the WordPress. Just changing the parents, and put the doings as now the elements with the arrows, only without arrows but a space simply..., would that work?
