### ISSUE TITLE
last issues

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#62]
- the link to art resources transfer should open in new tab

- the text on the first page of understandings should be “about”

- change right-column padding-left from 5px to 20px

- change right-column padding-right from 5px to 30px

- please add style for links in small text, for example prompt (see footnote 2 in http://resources.artresourcestransfer.org/#what for example) text size of the links should be 12px and -2px offset. link should hover black, not blue

- understandings should work like this, final now:
Reading is a creative act
Knowing 1: Close Reading (one title/post)
Knowing 2: Making Connections
Knowing 3 Debatable Questions
– Doing I (en-dash) Doing II – Doing III – Doing XY –

thanks!

**Comment by pwrstudio** [comment]
Changes made now!

**Comment by br092616** [comment]
great thanks. How about the scaling on the phone, could that be 'switched off'? and just asking: for a 13inch laptop or iPad, would there be an easy way to scale the entire site down a little, have everything be smaller a little? Alejandro wondered for a way to avoid scrolling in the left column.

**Comment by br092616** [comment]
the main menu and column seems to be moving when navigating from about>what to about>who

**Comment by br092616** [comment]
can we delete the hyphen at the beginning of the knowing, and change the en dash after to a colon, as in knowing 1
<img width="1292" alt="screen shot 2016-10-10 at 12 00 14" src="https://cloud.githubusercontent.com/assets/22127585/19232654/3b706546-8ee1-11e6-80de-c4bacfd6d850.png">
the hyphen can also go away for Doings. Works well with the dashes after I think.

**Comment by br092616** [comment]
forgive me, when you get to Understandings from the main menu, ideally "About" should be blue, as long as it's open

**Comment by br092616** [comment]
in http://resources.artresourcestransfer.org/ways-of-reading/ is ther a way for them to add a empty line between about and the list of names? if not, could you add this, please?

**Comment by br092616** [comment]
same in http://resources.artresourcestransfer.org/activating-the-catalog/ I guess

**Comment by br092616** [comment]
almost there!

**Comment by br092616** [comment]
ok I'm sorry. Now that there's an italic format for the serif I'm afraid there's no way of avoiding an italic also for the sans serif...

[readingsans-Italics.otf.zip](https://github.com/pwrstudio/rr_wp/files/519274/readingsans-Italics.otf.zip)

**Comment by br092616** [comment]
Now looking at it, I thought our serif looks like Times. Which from what I see it actually is?

Should be Nimbus Serif however, the one I had sent, or readingserif - if I change it it needs a little letter spacing and a tiny but larger, to be the same as what we have now.

Or is that a problem? Let me know.

<img width="1292" alt="screen shot 2016-10-10 at 17 31 08" src="https://cloud.githubusercontent.com/assets/22127585/19241806/9fe4f1c0-8f10-11e6-9233-cfe1e7b46556.png">
<img width="1292" alt="screen shot 2016-10-10 at 17 31 33" src="https://cloud.githubusercontent.com/assets/22127585/19241807/9fe79b32-8f10-11e6-9dc7-6db264b333f3.png">
[Nimbus Serif.zip](https://github.com/pwrstudio/rr_wp/files/519867/Nimbus.Serif.zip)

**Comment by pwrstudio** [comment]
`the main menu and column seems to be moving when navigating from about>what to about>who, also the colophon menu is moving somehow`

I am not seeing this in any browser. might be a scrollbar appearing at some window widths, that would change the size of the window slightly

`great thanks. How about the scaling on the phone, could that be 'switched off'? and just asking: for a 13inch laptop or iPad, would there be an easy way to scale the entire site down a little, have everything be smaller a little? Alejandro wondered for a way to avoid scrolling in the left column.`

there is no adjustments done for different screen sizes now. I can either try to control it or not. 

`forgive me, when you get to Understandings from the main menu, ideally "About" should be blue, as long as it's open`

Done

`Now looking at it, I thought our serif looks like Times. Which from what I see it actually is?`

You are tight. they are very similar though! changed to nimbus now.

`ok I'm sorry. Now that there's an italic format for the serif I'm afraid there's no way of avoiding an italic also for the sans serif...`

added.

`in http://resources.artresourcestransfer.org/ways-of-reading/ is ther a way for them to add a empty line between about and the list of names? if not, could you add this, please?`

added

**Comment by br092616** [comment]
if you look at about, or colophon
<img width="1292" alt="screen shot 2016-10-10 at 21 03 38" src="https://cloud.githubusercontent.com/assets/22127585/19247832/3ed3e900-8f2d-11e6-805c-604674eaf9de.png">
<img width="1292" alt="screen shot 2016-10-10 at 21 03 42" src="https://cloud.githubusercontent.com/assets/22127585/19247834/3edcb134-8f2d-11e6-95b5-0a4158908fc6.png">
<img width="1292" alt="screen shot 2016-10-10 at 21 03 52" src="https://cloud.githubusercontent.com/assets/22127585/19247833/3edc17e2-8f2d-11e6-8c98-a526b7e1a86d.png">
<img width="1292" alt="screen shot 2016-10-10 at 21 03 56" src="https://cloud.githubusercontent.com/assets/22127585/19247835/3edfc996-8f2d-11e6-83d2-3774b738d17d.png">

**Comment by br092616** [comment]
yes somehow there's a second scrollbar coming in on the right side
<img width="1292" alt="screen shot 2016-10-10 at 21 06 41" src="https://cloud.githubusercontent.com/assets/22127585/19247916/884e799c-8f2d-11e6-970e-9047bbfa8dd0.png">

**Comment by br092616** [comment]
cool thank you - would you add letter-spacing 0.01em?

**Comment by br092616** [comment]
for the phone, it would be great I think if the column width would stay the same as on the large screen, and not become more narrow.

**Comment by pwrstudio** [comment]
comment 1 and 2 changed now. regarding comment 3: i can not get into adaption for the phone on the current budget.

**Comment by br092616** [comment]
another typography detail that looks off a bit - the external links within the large text should be the same size as the footnote numbers, here's a screenshot.

<img width="1292" alt="screen shot 2016-10-10 at 22 21 35" src="https://cloud.githubusercontent.com/assets/22127585/19249941/3ec6a2e4-8f38-11e6-9adb-6d407bfcd8cb.png">

**Comment by br092616** [comment]
not sure but if with say 50 euros it would be possible to add a minimum and maximum limit to the width of the columns, if that makes sense, I would take it from my part. Would be great to avoid having it look weird on very small or very large screens I think, if I don't have an idea how... thx!

**Comment by br092616** [comment]
oh and in understandings with the knowings, it should be a colon not a dash 
<img width="1387" alt="screen shot 2016-10-10 at 22 31 26" src="https://cloud.githubusercontent.com/assets/22127585/19250204/6672e3f6-8f39-11e6-8dc6-66489ad72731.png">

**Comment by br092616** [comment]
the serif italics won't display in Safari I think

![screen shot 2016-10-11 at 15 37 47](https://cloud.githubusercontent.com/assets/22127585/19272468/f3426b8c-8fc8-11e6-8ba1-ff28c105a182.png)

**Comment by pwrstudio** [comment]
changes made

re: phone, the layout looks fine on all phone i have tried: iphone, android, windows phone:

![bs_winphone_mobile_nokia lumia 930-8 1-1080x1920](https://cloud.githubusercontent.com/assets/8209990/19325829/37e3ae0e-90c8-11e6-8b38-4c20d9e324b9.jpg)
![bs_realdroid_mobile_google nexus 6-6 0-1440x2560](https://cloud.githubusercontent.com/assets/8209990/19325833/380c34aa-90c8-11e6-9938-f94b30fde37c.jpg)
![bs_realdroid_mobile_samsung galaxy s5-4 4-1080x1920](https://cloud.githubusercontent.com/assets/8209990/19325832/37ea30e4-90c8-11e6-9fab-ca6da9142b08.jpg)
![bs_realios_mobile_iphone 6-8 0](https://cloud.githubusercontent.com/assets/8209990/19325830/37e678e6-90c8-11e6-82d9-318ae1d9a983.jpg)
![bs_realios_mobile_iphone 6s plus-9 0](https://cloud.githubusercontent.com/assets/8209990/19325831/37e735ba-90c8-11e6-817f-8f1276687fdf.jpg)

**Comment by br092616** [comment]
cool thank you. the problem is when you tap or zoom in to read, the column becomes so narrow - or if you’re looking at it on a large screen, it becomes extremely wide...












benedikt reichenbach 
www.benediktreichenbach.com 
+49 1 76 23 92 74 56

**Comment by pwrstudio** [comment]
hmm not here. could you send screen shots? what phone are you on?

re: large screen yes, this is true. I can limit it to lines of a certain letter-count. what number?

**Comment by br092616** [comment]
how about 60 letters for the large serif and 75 letter for the small serif… or 70 in general

iPhone 5

![img_3698](https://cloud.githubusercontent.com/assets/22127585/19326600/7cbaf30e-90cb-11e6-8c59-1e5a6e37d7db.PNG)
![img_3700](https://cloud.githubusercontent.com/assets/22127585/19326599/7cb8bbca-90cb-11e6-8001-65c05d958971.PNG)
![img_3699](https://cloud.githubusercontent.com/assets/22127585/19326601/7cbf1696-90cb-11e6-8e9b-fd39be9f5012.PNG)

**Comment by br092616** [comment]
ah forgive me - links in large text look great now, only the links and in the small text now seem larger than before also - should be as before if possible

**Comment by pwrstudio** [comment]
better now on the iphone?

**Comment by br092616** [comment]
yes and no - text is cut off on the right  when zooming in to read, can't move to the end.
thanks!

**Comment by br092616** [comment]
this didn’t upload I think - with this and the last little detail on the small format of the links, I think we’re good!?

Thanks,
Benedikt



benedikt reichenbach 
www.benediktreichenbach.com 
+49 1 76 23 92 74 56

**Comment by pwrstudio** [comment]
small links change from 14px to 13px

re:iphone: should look like this on zoom now. 

![screen shot 2016-10-13 at 1 28 59 pm](https://cloud.githubusercontent.com/assets/8209990/19347550/a4173d44-9149-11e6-84b1-7153ef57e812.png)

**Comment by br092616** [comment]
great thanks looking great on the phone now!

small links problem is also the position, should be top:-2px instead of -6px

**Comment by pwrstudio** [comment]
done!

**Comment by br092616** [comment]
this thing in understandings>doings, then a drink!?

one last thing here: either the first doing needs a dash, too. But that might be weird. Or the number only, not also the dash, would react on hover, along with “Doings:”… if possible…?

**Comment by br092616** [comment]
Alejandro wrote te captions in bibliography>images are not working correctly. Checked quickly I'm afraid he's right... woudl be great if you could check, too, thanks!

**Comment by br092616** [comment]
Kylie writing, with one note to add - "sometimes the linking seems out of synch, i.e. if you click from one part within a section to another (Understandings > Doings, for example), the back button returns you to the section home page, or sometimes doesn't seem to work at all. It seems minor but thought I would flag it in any case."
